AccessToken Store & Non-Interactive Authentication
lpgera/dirigera pull request #1
Opened 2023-02-23 02:31 UTC by cseitz

- A combined getter/setter can be used in place of `accessToken` to save and retrieve the token.
- The `authenticate` procedure no longer uses readline to wait for user input, but instead attempts to authenticate every second until it works.
  - Definitely making unnecessary requests, but does it even matter considering we're talking to a device on our own network?
 
I tried to keep the program behavior the same. My changes only take place if the accessToken store is specified.
 - You can still `npx dirigera authenticate`, but now its unnecessary because the program will prompt you to press the button and temporarily cease execution till you do so. From that point forward, your store will save the token and any future runs of the program will simply pull it from wherever you desire.

```ts
const client = createDirigeraClient({
    gatewayIP: '0.0.0.0',
    accessToken: async (accessToken) => {
        const file = 'token.txt';
        if (accessToken) {
            await writeFile(file, accessToken)
        }
        try {
            return await readFile(file, 'utf8');
        } catch (err) {
            return null;
        }
    },
})
```

2023-02-28 18:00 UTC, lpgera commented
Hey @cseitz and welcome to the repository! Congrats on being the first collaborator to my project! 🎉

> * A combined getter/setter can be used in place of `accessToken` to save and retrieve the token.

This is a brilliant idea!

> * The `authenticate` procedure no longer uses readline to wait for user input, but instead attempts to authenticate every second until it works.
>   
>   * Definitely making unnecessary requests, but does it even matter considering we're talking to a device on our own network?

I don't think the requests should cause any issues, but I left some comments on your suggested changes. Some testing with the gateway will also be needed before I can merge to avoid any lockups or bans from the gateway.

> * You can still `npx dirigera authenticate`, but now its unnecessary because the program will prompt you to press the button and temporarily cease execution till you do so.

While this is true, I'd like to keep supporting use cases in which the library users provide the token from an environment variable such as in a Docker container. Which is still okay with your implementation, but I just wanted to highlight that there are different approaches to keep in our minds.

I'm excited to continue working with you to get this PR merged!

2023-10-01 19:04 UTC, zinen commented
I really need this to support non-Interactive authentication. And also support the idea of continuously pull status from while waiting for the push of the button. 

When will this get merged?

2023-10-01 20:18 UTC, lpgera requested changes
At one point in time I started reviewing the PR, but then totally forgot to submit my comments. That's my bad. 🤦‍♂️

@cseitz would you mind rebasing the PR to the latest version of main?

2023-10-01 20:18 UTC, lpgera commented on README.md
> +- [Dirigera](#dirigera)
Why the new additional level in the ToC? Doesn't seem to be useful for the reader to jump to the top from here, but I'm wondering if you used some kind of IDE feature to generate this that I'm not aware of. 🙂

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> -      const rl = readline.createInterface({
I'm quite happy about the removal of the `readline` dependency, as not relying on an interactive shell opens up a lot of possibilities regarding the library's usage, however you forgot to remove the import and `tsc` reports the following error now:

```
src/index.ts:1:1 - error TS6133: 'readline' is declared but its value is never read.

1 import readline from 'readline/promises'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> + */
```suggestion
```

I'd like to keep comments in the codebase to the minimum and this one seems a bit unnecessary given all the info in the readme.

I'd much rather want the behavior to be documented as unit tests, but I haven't set up the proper test environment yet, so unfortunately it has to wait.

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> +  accessToken =
With the introduction of the `AccessTokenStore` it feels like there's a lot of type information getting lost with just reassigning the `accessToken` here. 🤔 

How about something like this instead?

```
export async function createDirigeraClient(options: {
  gatewayIP?: string
  accessToken?: string | null | AccessTokenStore
}) {
  const { gatewayIP, accessToken: accessTokenOrStore } = options
  const accessTokenStore =
    typeof accessTokenOrStore === 'function' ? accessTokenOrStore : null
  let accessToken =
    typeof accessTokenOrStore === 'function'
      ? await accessTokenOrStore()
      : accessTokenOrStore

\\ ...
```

This eliminates the need for `@ts-ignore` in the `initializeWebSocket` call below.

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
>        })
I'd suggest reverting these lines and fixing the type error with my suggestion above or with a similar solution!

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> +          .catch((err) => ({ access_token: undefined }))
The `err` parameter is unused and `tsc` throws an error.

```suggestion
          .catch(() => ({ access_token: undefined }))
```

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> +      const { access_token: newAccessToken }: { access_token: string } =
I believe you can get rid of this `@ts-ignore` if you specify the typing in the `json()` call's type parameter instead:

```
      const { access_token: newAccessToken } =
        await gotInstance
          .post(`oauth/token`, {
            form: {
              code,
              name: os.hostname(),
              grant_type: 'authorization_code',
              code_verifier: codeVerifier,
            },
          })
          .json<{ access_token: string }>()
          .catch(() => ({ access_token: undefined }))
```

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> +    }
Is this really necessary? Can't we just keep the `gotInstance` as a `const`? I think assigning the `accessToken` in the client instance's scope should take care of passing the header to the requests already.

2023-10-01 20:18 UTC, lpgera commented on src/index.ts
> +        return await getAccessToken()
I don't mind the repeated requests to the gateway, but I'm wondering if there should be a maximum amount for the retries instead of just being stuck in a loop indefinitely if there's no button press. What's your take on this?

2024-01-09 06:03 UTC, zinen commented
Any updates on this PR?

2024-01-11 17:36 UTC, lpgera commented
Sorry, but I've been focusing much more on covering the available gateway functionalities and providing better typings for the existing features. Which is still lacking in many places at the moment, such as the websocket events.

However, I'd like to understand your need better @zinen. If the `authenticate()` method had a version which wouldn't require input on `stdin`, but it'd rather perform a polling (with a sensible timeout), would that be working for you?

2024-01-11 19:02 UTC, zinen commented
I would say you. My case is that i wanna include this module inside another system. The system support timeout and event emitters. But no access to console must be required. All info/returned text must be piped back to the app via yielded info from a async job or callback.

2024-01-13 18:24 UTC, lpgera commented
Authentication works without console input starting from version 0.13.0.

2024-01-13 18:24 UTC, closed without merging