add startupOnOff startToggle mode for lights and outlets
lpgera/dirigera pull request #13
Opened 2024-12-08 17:27 UTC by storm84

Noticed that startToggle mode was missing for lights and outlets. Tested it out on both lights and outlets, was not sure if it would work for outlets since it is not possible to set within the IKEA app but it works just fine for both.

2024-12-09 13:39 UTC, lpgera requested changes
Thanks for noticing and adding this feature to the types! May I ask you to also extend the two related comments in the README.md file to make it slightly easier to notice for users of the library?

2024-12-09 16:34 UTC, storm84 commented
> Thanks for noticing and adding this feature to the types! May I ask you to also extend the two related comments in the README.md file to make it slightly easier to notice for users of the library?

It's done, just glad I'm able to help out :)

2024-12-10 19:03 UTC, lpgera approved these changes

2024-12-10 19:04 UTC, merged

2024-12-10 19:24 UTC, lpgera commented
Thanks again for your contribution! I've just published version 1.3.0 including this change.